### ISSUE TITLE
Testlink upgrade - 1.19.18

### ISSUE THREAD

**Issue by viictorh** [kinow/testlink-java-api#120]
Hello.

I would like to know if the lastest version released (1.9.17-1)  is compatible with the lastest version of testlink (1.19.18), or the last number is the compatibility between each other (17 -> 18, so, incompatible so far).

Our QA team updated the testlink (from 1.19.14) and now we're facing issues to read attachments and send results. I updated testlink-java-api version but it didn't fix, so we had to change the php class to get attachments on testlink website and API.

On Testlink tlAttachmentRepository.class.php, method getAttachmentIDsFor($fkid,$fkTableName) changed querie to:
`SELECT id FROM attachments WHERE (fk_id = 9227 OR fk_id = (SELECT id AS tcversion_id FROM nodes_hierarchy NHTCV WHERE NHTCV.parent_id = 9227 AND NHTCV.node_type_id = 4 ORDER BY id DESC LIMIT 1)) ORDER BY date_added DESC`

Thanks!

**Comment by kinow** [comment]
Hi @viictorh , I have not tested with the latest versions of TestLink.

>or the last number is the compatibility between each other (17 -> 18, so, incompatible so far).

The version scheme of the API is as follows

${TESTLINK_VERSION}-${INTERNAL_RELEASE_COUNTER}.

So for TestLink 1.19.18, we would have a release similar to `testlink-java-api-1.19.18-0` as a release that is compatible with 1.19.18.

>I updated testlink-java-api version but it didn't fix, so we had to change the php class to get attachments on testlink website and API.

If you have time to create a pull request to support 1.19.18, I'd be happy to set up the dev environment to test it. Otherwise, once I have spare time to work on this I'll try to release a new version compatible with whatever is the latest version of TL (normally takes a long time, as I am not using TestLink at the moment, nor receiving any sponsor to maintain the project ATM)

Hope that helps!
Bruno

**Comment by kinow** [comment]
@viictorh , I had some spare time waiting for Travis builds today near lunch break, did a triage of issues, and realized there's some very old tickets with no reply. In two weeks I will have a long break, so planning to work on a new release soon, where I will try to address every issue, and include as much as possible of the new API.

If you have any other requests, that's the time to put them in :-)

Thanks!

**Comment by viictorh** [comment]
Thanks for the feedback @kinow.  
That's all for know.

**Comment by kinow** [comment]
Heads up, looks like the latest version is 1.9.19: https://github.com/TestLinkOpenSourceTRMS/testlink-code/tree/1.9.19

As I have few development cycles, I feel like it's best to update to the latest, which hopefully will be compatible for a while.
