### ISSUE TITLE
Reporting test results from soapUI to Testlink with result=NOT_RUN fails

### ISSUE THREAD

**Issue by lazarenok** [kinow/testlink-java-api#42]
Hi!
I'm using soapUI 4.0.1, testlink-java-api-1.9.8-1, testlink-api-client-2.0.
The problem that I encountered is the following: 

In my soapUI project I have a groovy script that creates a file for execution results; second groovy script that loops through all Test Steps for each Test Case and depending on testStep.assertionStatus.toString (UNKNOWN, VALID or FAILED) writes results to this file, and the third script that reads results from the file and using testlinkAPIClient.reportTCResult sends results to TestLink. Parameter "ExecutionStatus status" for reportTCResult can be ExecutionStatus.PASSED, ExecutionStatus.FAILED or ExecutionStatus.NOT_RUN. The first two work fine, but when it gets to NOT_RUN I have error message "ERROR:br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException: The status code (n) provided is not valid!" 

Maybe I'm doing smth wrong...I don't know... Did anyone have the same issue?

**Comment by rajaguruc** [comment]
Hi,

I have a same requirement, update the testcase status. There is no API available.

Please let me know is there any way.

Thanks in advance.

**Comment by kinow** [comment]
Probably the easiest way to learn is through the tests

https://github.com/kinow/testlink-java-api/blob/master/src/main/java/br/eti/kinoshita/testlinkjavaapi/TestCaseService.java

The API is a bit outdated, so some adjustments may be necessary (pull requests/patches welcome :-) )

**Comment by kinow** [comment]
Closing as I believe the issue was about setting the result status to NOT_RUN (which is not allowed by TestLink).

**Comment by rajaguruc** [comment]
Hi Kinow,

Thanks for your reply. 

My requirement is to get and update the test-case status (i.e.) DRAFT,FINAL, FUTURE and etc. I am able to see enum namely "TestCaseStatus.java" in the testlink-java-api-1.9.13.jar but no api to get and update the testcase status. In model "TestCase.java", there is no variable (getter/setter) for testcase status. Can you please let me know.

Regards,
C.Rajaguru

**Comment by kinow** [comment]
Hi Rajaguru,

Can't promise any work on the API right now. Got a backlog at $work, and other projects that I'm planning to start development cycles to fix/release issues.

Might be easier when you have some code to show where you are struggling (pull request, gist, etc). Unless it is related to this issue, let's move the conversation elsewhere, otherwise everyone watching it (4 people) gets a notification for that :-)

**Comment by rajaguruc** [comment]
Thanks Kino. Is it fine, can I communicate via email instead of forum.

I am trying to get "Testcase" object by specifying plan id and build and
able to get "TestCase" object but no api (getter/setter) is available in
"TestCase.java" to get the status also no api available to update the
testcase status.

Following Java snippet:

*public Map<Integer, TestCase> getTestcasesForTestPlanAndBuild(int planId,
int buildId) {*
* Map<Integer, TestCase> testcaseMap = new HashMap<Integer, TestCase>();*
* try {*
* TestCase[] testcaseAry = getTestLinkAPI().*
*
getTestCasesForTestPlan(planId,null,buildId,null,null,null,null,null,null,null,null);*
* for (int ix = 0; ix < testcaseAry.length; ix++) {*
* TestCase testCase = testcaseAry[ix];*
* System.out.println("testCase ::: "+testCase.toString());*
* testcaseMap.put(testCase.getId(), testCase);*
* }*
* } catch(Exception e) {*
* System.out.println("Exception occurred :: getTestcasesForTestPlan ::");*
* e.printStackTrace();*
* }*
* return testcaseMap;*
* }*

Please find the attachment, screen-shot for more info:

**Comment by kinow** [comment]
Your comments are still on GitHub. If you are seeing this as an e-mail, it is actually a GitHub notification. Replying it, automatically creates a comment in the closed ticket and again notifies everyone.

Locking conversation.
