### ISSUE TITLE
Execute step by step and write back the result 

### ISSUE THREAD

**Issue by sabriBoussetha** [kinow/testlink-java-api#78]
Hello, 

I'm trying to execute each step and update its execution status, separately from the rest of steps of a test case.
Actually, I know that the current version 1.9.14 does not support that, but I tried some changes on client side, more precisely on reportTCResult(...) from TestCaseService Class, but no positif results yet. 
So I want to know if there is any way to do that? Thanks in advance for your answer.

Have a great day.

**Comment by kinow** [comment]
Hi @sabriBoussetha 

The Java API is simply a facade for the PHP API. If there are methods in the TestLink API for executing each step separately, we can definitely implement - if have already not - in the Java layer.

Otherwise, client customizations are not really done in the API. You are free to have those modifications in your project, but in order to keep maintenance easy, we try to keep the Java layer "dumb", and simply pass parameters to TestLink.

Hope that helps.
