### ISSUE TITLE
Need a new function named getTestCaseBugs

### ISSUE THREAD

**Issue by lijie-advantech** [kinow/testlink-java-api#82]
I need a function get bugID for a testcase, I found testlink already have function named getTestCaseBugs in version 1.9.14, you can see https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/1.9.14/lib/api/xmlrpc/v1/xmlrpc.class.php 
![1](https://cloud.githubusercontent.com/assets/20916286/20994503/c260d11c-bd2b-11e6-8429-2e6c17da6393.jpg)

**Comment by kinow** [comment]
Excellent @lijie-advantech ! Will try to include it in the next release. Patches/pull requests welcome as well, should you have time :-)

Last development cycle I had, I had to postpone changes since there was a bug preventing TL 1.9.15 (IIRC) from working correctly. Might try a release around new year's eve, or somewhere in January.

**Comment by lijie-advantech** [comment]
@kinow  Thank you for your reply. I'm not good at this, sorry for that.

#81 also need several new parameters, I'd be glad if you would try a release with this function as well, Thank you very much

**Comment by kinow** [comment]
Not a problem @lijie-advantech having someone to test the release is already a great help :-) thanks
