### ISSUE TITLE
TestCase External ID

### ISSUE THREAD

**Issue by vherasme** [kinow/testlink-java-api#92]
Hi,

I am trying to use the function:

`Execution e = API.getLastExecutionResult(testPlanId, testCaseId, testCaseExternalId);`

in order to get Execution information. I am confused regarding the third parameter, **testCaseExternalId**, because the method `TestCase.getFullExternalId();` returns a String so I dont know what to use as a **testCaseExternalId**. Can you help me with this ?

**Comment by kinow** [comment]
Oh, good question @vherasme . Let me check what's going on...

**Comment by kinow** [comment]
@vherasme I think this confusion is a historical issue. Looking at the PHP code, I can see [`externalId`](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/130dbb6a050f3311df09f37630e9389d0dfcbb42/lib/functions/testcase.class.php#L5202) and `fullExternalId`. 

There's also some code checking if external ID is numeric: https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/130dbb6a050f3311df09f37630e9389d0dfcbb42/lib/functions/testcase.class.php#L2947

The code doesn't look much different than what I saw some years ago. I still cannot confirm from looking at the code in GitHub UI (not using IDE right now) whether that's an int or string. Might need more time to confirm, and see why we have what we have in Java, and how we could improve it.

If you have any suggestions, feel free to update this issue or raise a pull request and I'll take a look.

Thanks!
Bruno

**Comment by kinow** [comment]
Ok, found out that full external ID is the prefix + `-` + external ID. Turns out we had the external ID in some methods, as `external_id`... but in other methods it was returned as `tc_external_id`.

Now we are collecting both (if the first is `null`, we just try the other one). Added a `externalId` property to `TestCase` too, so you should be able to use the new method now.

Thanks!
