### ISSUE TITLE
Procedure for Testlink 

### ISSUE THREAD

**Issue by cgprakash** [kinow/testlink-java-api#94]
can please provide step by step procedure for testlink api's:
1.addTestCaseToTestPlan
2.reportTestCaseResult
3.createBuild

**Comment by kinow** [comment]
Sorry @cgprakash , not enough bandwidth to work on issues not related to bugs or new features. There are some tests in the project showing how to use certain methods that may help you with what you describe above.

Otherwise, feel free to post os StackOverFlow. You might get some answers over there too (check if there are no similar questions first). Also, the Jenkins TestLink plugin does something similar to what you are asking for. Checking its source code may help you.

Cheers
Bruno
